# Examen de Sistemas Inteligentes junio 2024
## Parte práctica
### Nombre del alumno

Pon aquí tu nombre.

En el laboratorio, se entrega un Jupiter Notebook con las respuestas. El dataset está subido al
campus.
Disponemos de un dataset sobre demencia con los siguientes campos:
• Subject ID: identificación del paciente.
• MRI ID: identificación de la visita al médico.
• Group: Grupo al que pertenece, que puede ser:
– Demented: Ha sido diagnosticado con la enfermedad desde el principio.
– Nondemented: No ha sido diagnosticada la enfermedad en ningún
momento.
– Converted: A 14 pacientes se le diagnosticó mal inicialmente y
acabaron teniendo demencia.
• Visit: número de visita.
• MR Delay: Deley desde la última consulta.
• M/F: Género.
• Hand: Si son diestros o no.
• Age: Edad
Y los siguientes valores que son pruebas médicas realizados a los pacientes:
SES,MMSE,CDR,eTIV,nWBV,ASF
En el dataset hay varios pacientes, cada uno de ellos han visitado el médico al
menos 2 veces. Queremos construir un modelo que prediga el estado del paciente
entre Demented, Nondemented y Converted. Con esto podremos identificar a
tiempo sobre todo aquello pacientes a los que las pruebas diagnósticas iniciales
indicaba que no eran dementes, pero que acabaron siéndolo.

Ejercicio 1 (1 punto): Limpia el dataset de errores y elementos que no sean
relevantes. Justifica en una celda de markdown las decisiones que has tomado.

Ejercicio 2 (1.5 puntos): Usa el Perceptrón multicapa de SKLearn. El resultado mínimo que
debéis conseguir de precisión es de un 65%. Dejad bien claro cuál es el modelo con el que
finalmente os quedáis.

Ejercicio 4 (1.5 puntos): Usa el algoritmo Decision Tree de Sklearn para construir un segundo
modelo. Calcula accuracy y la matriz de confusión. El resultado mínimo que debéis conseguir
de precisión es de un 85% (random_state=42)

Ejercicio 4 (1 Punto) compara los resultados de ambos y justifica con cual te quedarías

**Instrucciones:** Carga el fichero pet_adoption_data.csv, y contexta las preguntas debajo de los encabezados.

In [47]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder

datos = pd.read_csv("dementia_dataset.csv")

### Ejercicio 1

Limpia el dataset de errores y elementos que no sean relevantes. Justifica en una celda de markdown la decisiones que has tomado.

In [48]:
#Variables usadas para hacer debug

filas_ejemplo = 3
debug = True
porcentaje_significativo = 0.05

display(datos.head(filas_ejemplo))

if(debug):
    # Número filas y columnas
    display(f"Filas existentes {datos.index.size} Columnas existentes {datos.columns.size}")

    # Datos únicos de cada columna
    for i in datos.columns:
        display(f"columna= {i}" ,datos[i].unique())

#Buscamos filas o columnas duplicadas
filas_duplicadas = datos.duplicated()
numero_filas_duplicadas = filas_duplicadas.sum()

if(debug):
    print(f"Número filas duplicadas: {numero_filas_duplicadas}")

if(numero_filas_duplicadas > 0):
    datos = datos.drop_duplicates()
    
#Buscamos nulos y los tratamos

if debug:
    display("lista de nulos",datos.isnull().sum())

if debug:
    display("pre tratados " ,datos[datos.isnull().any(axis=1)])
    total_valores_nulos = datos.isna().sum()
    display(total_valores_nulos)

# 373 son pocos datos. Trataré de sustituir por la media los dos nan de MMSE. 
# Haré drop de SES si 19 es un porcentaje significativos

num_nan_ses = datos['SES'].isna().sum()
total_filas = datos.index.size
porcentaje_nan_ses = (num_nan_ses / total_filas) * 100

if debug:
    print(f"Porcentaje de filas con SES como NaN: {porcentaje_nan_ses:.2f}%")
    
if(porcentaje_nan_ses > porcentaje_significativo):
    datos = datos.dropna(subset=['SES'])
    print("Se hizo drop de SES")
else:
    media_SES = datos["SES"].mean()
    datos["SES"] = datos["SES"].fillna(media_SES)
    print("Se rellenó los valores nulos de SES con la media de la columna")

#Cambiamos Nan por media. Calcularé también la moda pero no la usaré. Dependinedo del problema puede ser más interesante que la media

media_MMSE = datos["MMSE"].mean()
datos["MMSE"] = datos["MMSE"].fillna(media_MMSE)

# Devuelve una Serie con el valor o los valores más frecuentes (la moda) de la columna. 
# Si hay más de un valor con la misma frecuencia máxima, devuelve todos ellos.
moda_MMSE = datos["MMSE"].mode()[0]

if debug:
    print(f"Media: {media_MMSE}")
    print(f"Moda: {moda_MMSE}")
    

#Desechamos columnas que no aportan información

#Eliminamos los id de los pacientes. No aportan a los estudios

datos = datos.drop("Subject ID", axis=1) # axis = 1 -> Elimina la columna
datos = datos.drop("MRI ID", axis=1)

#Todos son diestros
datos = datos.drop("Hand", axis=1)

#Pasamos las columnas pertinentes a enteros
arrayToInt =["MMSE", "SES"]

for i in arrayToInt:
    datos[i] = np.ceil(datos[i]).astype(int)

#Pasamos columnas binarias a 0 y 1
datos["M/F"] = datos["M/F"].map({
    'M': 0,
    'F': 1
})

if(debug):
    display(datos.head(filas_ejemplo))
    
    
# Queremos adivinar la columna Group
# No estoy seguro de si para predecir este resultado será mejor codificarla con OHE o OHE label. Voy a preparar ambas maneras.

encoded_Group = datos["Group"].map({
    'Converted': 2,
    'Demented': 1,
    'Nondemented': 0
})
    
#Pasamos el OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

array_OHE = ["Group"]

for i in array_OHE:
    aux_HOT= encoder.fit_transform(datos[i].to_numpy().reshape(-1,1))
    if debug:
        display(i)

    column_names = encoder.get_feature_names_out([i])

    datos=pd.concat([datos, pd.DataFrame(aux_HOT,columns=column_names,index=datos.index)],axis=1)
    #eliminamos la columna ya tratada
    datos=datos.drop(i,axis=1)
    
display(datos.head(filas_ejemplo))

#Separamos los datos con los que trabajaremos. Los que debemos predecir y los que usaremos para predecir

X = datos
arrayToDelete = ["Group_Converted", "Group_Demented", "Group_Nondemented"]

for i in arrayToDelete:
    X = X.drop(i, axis=1)
    
Y = pd.concat([datos[arrayToDelete], encoded_Group], axis=1)


if(debug):
    print("Datos a usar para adivinar")
    display(X.head(filas_ejemplo))
    print("Datos a adivinar")
    display(Y.head(filas_ejemplo))
    




Subject ID         MRI ID        Group  Visit  MR Delay M/F Hand  Age  EDUC  \
0  OAS2_0001  OAS2_0001_MR1  Nondemented      1         0   M    R   87    14   
1  OAS2_0001  OAS2_0001_MR2  Nondemented      2       457   M    R   88    14   
2  OAS2_0002  OAS2_0002_MR1     Demented      1         0   M    R   75    12   

   SES  MMSE  CDR  eTIV   nWBV    ASF  
0  2.0  27.0  0.0  1987  0.696  0.883  
1  2.0  30.0  0.0  2004  0.681  0.876  
2  NaN  23.0  0.5  1678  0.736  1.046

'Filas existentes 373 Columnas existentes 15'

'columna= Subject ID'

array(['OAS2_0001', 'OAS2_0002', 'OAS2_0004', 'OAS2_0005', 'OAS2_0007',
       'OAS2_0008', 'OAS2_0009', 'OAS2_0010', 'OAS2_0012', 'OAS2_0013',
       'OAS2_0014', 'OAS2_0016', 'OAS2_0017', 'OAS2_0018', 'OAS2_0020',
       'OAS2_0021', 'OAS2_0022', 'OAS2_0023', 'OAS2_0026', 'OAS2_0027',
       'OAS2_0028', 'OAS2_0029', 'OAS2_0030', 'OAS2_0031', 'OAS2_0032',
       'OAS2_0034', 'OAS2_0035', 'OAS2_0036', 'OAS2_0037', 'OAS2_0039',
       'OAS2_0040', 'OAS2_0041', 'OAS2_0042', 'OAS2_0043', 'OAS2_0044',
       'OAS2_0045', 'OAS2_0046', 'OAS2_0047', 'OAS2_0048', 'OAS2_0049',
       'OAS2_0050', 'OAS2_0051', 'OAS2_0052', 'OAS2_0053', 'OAS2_0054',
       'OAS2_0055', 'OAS2_0056', 'OAS2_0057', 'OAS2_0058', 'OAS2_0060',
       'OAS2_0061', 'OAS2_0062', 'OAS2_0063', 'OAS2_0064', 'OAS2_0066',
       'OAS2_0067', 'OAS2_0068', 'OAS2_0069', 'OAS2_0070', 'OAS2_0071',
       'OAS2_0073', 'OAS2_0075', 'OAS2_0076', 'OAS2_0077', 'OAS2_0078',
       'OAS2_0079', 'OAS2_0080', 'OAS2_0081', 'OAS2_0085', 'OAS2

'columna= MRI ID'

array(['OAS2_0001_MR1', 'OAS2_0001_MR2', 'OAS2_0002_MR1', 'OAS2_0002_MR2',
       'OAS2_0002_MR3', 'OAS2_0004_MR1', 'OAS2_0004_MR2', 'OAS2_0005_MR1',
       'OAS2_0005_MR2', 'OAS2_0005_MR3', 'OAS2_0007_MR1', 'OAS2_0007_MR3',
       'OAS2_0007_MR4', 'OAS2_0008_MR1', 'OAS2_0008_MR2', 'OAS2_0009_MR1',
       'OAS2_0009_MR2', 'OAS2_0010_MR1', 'OAS2_0010_MR2', 'OAS2_0012_MR1',
       'OAS2_0012_MR2', 'OAS2_0012_MR3', 'OAS2_0013_MR1', 'OAS2_0013_MR2',
       'OAS2_0013_MR3', 'OAS2_0014_MR1', 'OAS2_0014_MR2', 'OAS2_0016_MR1',
       'OAS2_0016_MR2', 'OAS2_0017_MR1', 'OAS2_0017_MR3', 'OAS2_0017_MR4',
       'OAS2_0017_MR5', 'OAS2_0018_MR1', 'OAS2_0018_MR3', 'OAS2_0018_MR4',
       'OAS2_0020_MR1', 'OAS2_0020_MR2', 'OAS2_0020_MR3', 'OAS2_0021_MR1',
       'OAS2_0021_MR2', 'OAS2_0022_MR1', 'OAS2_0022_MR2', 'OAS2_0023_MR1',
       'OAS2_0023_MR2', 'OAS2_0026_MR1', 'OAS2_0026_MR2', 'OAS2_0027_MR1',
       'OAS2_0027_MR2', 'OAS2_0027_MR3', 'OAS2_0027_MR4', 'OAS2_0028_MR1',
       'OAS2_0028_MR2', '

'columna= Group'

array(['Nondemented', 'Demented', 'Converted'], dtype=object)

'columna= Visit'

array([1, 2, 3, 4, 5], dtype=int64)

'columna= MR Delay'

array([   0,  457,  560, 1895,  538, 1010, 1603,  518, 1281,  742,  576,
        854,  730, 1598,  643, 1456,  504,  707,  617, 1861, 2400,  489,
       1933,  756, 1563, 1164,  828,  578,  673,  609, 1234, 1779,  610,
       1099,  932,  446, 1588,  642, 1287, 1884,  405,  713, 1770, 2369,
       1123, 2029, 2508,  486,  567, 1204, 1331, 1008,  491,  352,  866,
        689,  575,  248,  647,  970, 1233,  395,  687, 1526, 1510,  842,
        846,  726,  622,  640, 1340,  212,  764, 1290,  873, 1651,  723,
       1351,  490,  830, 1282,  497,  451, 1438, 2163,  743,  432,  672,
       1415, 1870, 2386,  365,  580, 1705, 2288, 2517,  956, 1663, 1393,
        441, 1019,  584, 1435, 1209,  659,  670,  802,  754,  751,  563,
        680, 1345, 1047,  706,  817, 1412,  778, 1024,  661,  807, 1218,
       1752,  952, 1631, 1387, 1554, 2002,  465,  675,  729,  883,  766,
        881,  558,  570,  616, 1927, 1422,  733, 1713,  595,  597,  472,
       1192,  851, 1042, 2153, 2639, 1140,  737, 15

'columna= M/F'

array(['M', 'F'], dtype=object)

'columna= Hand'

array(['R'], dtype=object)

'columna= Age'

array([87, 88, 75, 76, 80, 90, 83, 85, 71, 73, 93, 95, 68, 69, 66, 78, 81,
       82, 77, 86, 92, 84, 72, 61, 64, 74, 60, 62, 91, 79, 89, 70, 94, 97,
       65, 67, 63, 96, 98], dtype=int64)

'columna= EDUC'

array([14, 12, 18, 16,  8, 20, 13,  6, 17, 15, 23, 11], dtype=int64)

'columna= SES'

array([ 2., nan,  3.,  4.,  1.,  5.])

'columna= MMSE'

array([27., 30., 23., 28., 22., 29., 24., 21., 16., 25., 26., 15., 20.,
       19.,  7.,  4., 17., 18., nan])

'columna= CDR'

array([0. , 0.5, 1. , 2. ])

'columna= eTIV'

array([1987, 2004, 1678, 1738, 1698, 1215, 1200, 1689, 1701, 1699, 1357,
       1365, 1372, 1272, 1257, 1457, 1480, 1447, 1482, 1333, 1323, 1230,
       1212, 1225, 1602, 1590, 1651, 1668, 1783, 1814, 1820, 1813, 1406,
       1398, 1423, 1587, 1606, 1597, 1911, 1926, 1313, 1316, 1247, 1250,
       1420, 1445, 1360, 1358, 1353, 1547, 1562, 1377, 1390, 1402, 1392,
       1430, 1463, 1307, 1311, 1466, 1450, 1460, 1453, 1336, 1329, 1359,
       1361, 1349, 1477, 1487, 1483, 1485, 1174, 1179, 1310, 1320, 1348,
       1289, 1295, 1314, 1640, 1665, 1451, 1331, 1332, 1317, 1322, 1476,
       1433, 1414, 1695, 1708, 1712, 1714, 1491, 1505, 1503, 1461, 1454,
       1474, 1484, 1500, 1264, 1275, 1362, 1456, 1599, 1569, 1580, 1315,
       1308, 1324, 1416, 1408, 1654, 1660, 1681, 1641, 1664, 1667, 1462,
       1459, 1464, 1957, 1928, 1440, 1438, 1455, 1444, 1428, 1475, 1470,
       1471, 1692, 1707, 1724, 1720, 1391, 1524, 1512, 1507, 1490, 1504,
       1151, 1143, 1536, 1520, 1848, 1931, 1631, 16

'columna= nWBV'

array([0.696, 0.681, 0.736, 0.713, 0.701, 0.71 , 0.718, 0.712, 0.711,
       0.705, 0.748, 0.727, 0.698, 0.703, 0.806, 0.791, 0.769, 0.752,
       0.738, 0.715, 0.72 , 0.697, 0.66 , 0.646, 0.759, 0.755, 0.761,
       0.693, 0.677, 0.666, 0.719, 0.805, 0.796, 0.662, 0.652, 0.695,
       0.783, 0.782, 0.775, 0.772, 0.737, 0.717, 0.734, 0.735, 0.822,
       0.817, 0.679, 0.676, 0.684, 0.733, 0.789, 0.773, 0.778, 0.729,
       0.709, 0.706, 0.742, 0.724, 0.771, 0.768, 0.76 , 0.766, 0.777,
       0.757, 0.685, 0.678, 0.731, 0.75 , 0.723, 0.691, 0.682, 0.794,
       0.788, 0.689, 0.744, 0.683, 0.837, 0.827, 0.756, 0.739, 0.707,
       0.747, 0.688, 0.721, 0.694, 0.722, 0.7  , 0.687, 0.69 , 0.728,
       0.704, 0.787, 0.774, 0.743, 0.741, 0.725, 0.674, 0.67 , 0.686,
       0.751, 0.792, 0.672, 0.661, 0.692, 0.758, 0.699, 0.78 , 0.762,
       0.781, 0.732, 0.708, 0.77 , 0.754, 0.726, 0.749, 0.74 , 0.669,
       0.663, 0.644, 0.68 , 0.786, 0.767, 0.812, 0.795, 0.819, 0.81 ,
       0.746, 0.716,

'columna= ASF'

array([0.883, 0.876, 1.046, 1.01 , 1.034, 1.444, 1.462, 1.039, 1.032,
       1.033, 1.293, 1.286, 1.279, 1.38 , 1.396, 1.205, 1.186, 1.213,
       1.184, 1.316, 1.326, 1.327, 1.427, 1.448, 1.433, 1.096, 1.104,
       1.063, 1.052, 0.985, 0.968, 0.964, 1.248, 1.255, 1.234, 1.106,
       1.093, 1.099, 0.919, 0.911, 1.337, 1.333, 1.407, 1.405, 1.236,
       1.214, 1.291, 1.297, 1.134, 1.124, 1.275, 1.263, 1.252, 1.261,
       1.227, 1.215, 1.199, 1.342, 1.339, 1.197, 1.21 , 1.202, 1.208,
       1.313, 1.32 , 1.29 , 1.301, 1.188, 1.18 , 1.181, 1.495, 1.488,
       1.329, 1.302, 1.362, 1.356, 1.335, 1.07 , 1.054, 1.317, 1.318,
       1.332, 1.189, 1.183, 1.225, 1.242, 1.036, 1.028, 1.025, 1.024,
       1.177, 1.166, 1.168, 1.207, 1.19 , 1.17 , 1.388, 1.376, 1.289,
       1.285, 1.098, 1.118, 1.111, 1.341, 1.239, 1.247, 1.061, 1.057,
       1.044, 1.069, 1.055, 1.053, 1.228, 1.2  , 1.203, 0.897, 0.91 ,
       1.219, 1.22 , 1.206, 1.229, 1.194, 1.193, 1.037, 1.018, 1.02 ,
       1.262, 1.151,

Número filas duplicadas: 0


'lista de nulos'

Subject ID     0
MRI ID         0
Group          0
Visit          0
MR Delay       0
M/F            0
Hand           0
Age            0
EDUC           0
SES           19
MMSE           2
CDR            0
eTIV           0
nWBV           0
ASF            0
dtype: int64

'pre tratados '

Subject ID         MRI ID     Group  Visit  MR Delay M/F Hand  Age  EDUC  \
2    OAS2_0002  OAS2_0002_MR1  Demented      1         0   M    R   75    12   
3    OAS2_0002  OAS2_0002_MR2  Demented      2       560   M    R   76    12   
4    OAS2_0002  OAS2_0002_MR3  Demented      3      1895   M    R   80    12   
10   OAS2_0007  OAS2_0007_MR1  Demented      1         0   M    R   71    16   
11   OAS2_0007  OAS2_0007_MR3  Demented      3       518   M    R   73    16   
12   OAS2_0007  OAS2_0007_MR4  Demented      4      1281   M    R   75    16   
134  OAS2_0063  OAS2_0063_MR1  Demented      1         0   F    R   80    12   
135  OAS2_0063  OAS2_0063_MR2  Demented      2       490   F    R   81    12   
207  OAS2_0099  OAS2_0099_MR1  Demented      1         0   F    R   80    12   
208  OAS2_0099  OAS2_0099_MR2  Demented      2       807   F    R   83    12   
237  OAS2_0114  OAS2_0114_MR1  Demented      1         0   F    R   76    12   
238  OAS2_0114  OAS2_0114_MR2  Demented      2       570   F    R   78    12   
322  OAS2_0160  OAS2_0160_MR1  Demented      1         0   M    R   76    12   
323  OAS2_0160  OAS2_0160_MR2  Demented      2       552   M    R   78    12   
356  OAS2_0181  OAS2_0181_MR1  Demented      1         0   F    R   74    12   
357  OAS2_0181  OAS2_0181_MR2  Demented      2       539   F    R   75    12   
358  OAS2_0181  OAS2_0181_MR3  Demented      3      1107   F    R   77    12   
359  OAS2_0182  OAS2_0182_MR1  Demented      1         0   M    R   73    12   
360  OAS2_0182  OAS2_0182_MR2  Demented      2       776   M    R   75    12   

     SES  MMSE  CDR  eTIV   nWBV    ASF  
2    NaN  23.0  0.5  1678  0.736  1.046  
3    NaN  28.0  0.5  1738  0.713  1.010  
4    NaN  22.0  0.5  1698  0.701  1.034  
10   NaN  28.0  0.5  1357  0.748  1.293  
11   NaN  27.0  1.0  1365  0.727  1.286  
12   NaN  27.0  1.0  1372  0.710  1.279  
134  NaN  30.0  0.5  1430  0.737  1.228  
135  NaN  27.0  0.5  1453  0.721  1.208  
207  NaN  27.0  0.5  1475  0.762  1.190  
208  NaN  23.0  0.5  1484  0.750  1.183  
237  NaN  27.0  0.5  1316  0.727  1.333  
238  NaN  27.0  1.0  1309  0.709  1.341  
322  NaN  27.0  0.5  1557  0.705  1.127  
323  NaN  29.0  1.0  1569  0.704  1.119  
356  NaN  26.0  0.5  1171  0.733  1.499  
357  NaN   NaN  1.0  1169  0.742  1.501  
358  NaN   NaN  1.0  1159  0.733  1.515  
359  NaN  23.0  0.5  1661  0.698  1.056  
360  NaN  20.0  0.5  1654  0.696  1.061

Subject ID     0
MRI ID         0
Group          0
Visit          0
MR Delay       0
M/F            0
Hand           0
Age            0
EDUC           0
SES           19
MMSE           2
CDR            0
eTIV           0
nWBV           0
ASF            0
dtype: int64

Porcentaje de filas con SES como NaN: 5.09%
Se hizo drop de SES
Media: 27.40960451977401
Moda: 30.0


Group  Visit  MR Delay  M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV  \
0  Nondemented      1         0    0   87    14    2    27  0.0  1987  0.696   
1  Nondemented      2       457    0   88    14    2    30  0.0  2004  0.681   
5  Nondemented      1         0    1   88    18    3    28  0.0  1215  0.710   

     ASF  
0  0.883  
1  0.876  
5  1.444

'Group'

Visit  MR Delay  M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF  \
0      1         0    0   87    14    2    27  0.0  1987  0.696  0.883   
1      2       457    0   88    14    2    30  0.0  2004  0.681  0.876   
5      1         0    1   88    18    3    28  0.0  1215  0.710  1.444   

   Group_Converted  Group_Demented  Group_Nondemented  
0              0.0             0.0                1.0  
1              0.0             0.0                1.0  
5              0.0             0.0                1.0

Datos a usar para adivinar


Visit  MR Delay  M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0      1         0    0   87    14    2    27  0.0  1987  0.696  0.883
1      2       457    0   88    14    2    30  0.0  2004  0.681  0.876
5      1         0    1   88    18    3    28  0.0  1215  0.710  1.444

Datos a adivinar


Group_Converted  Group_Demented  Group_Nondemented  Group
0              0.0             0.0                1.0      0
1              0.0             0.0                1.0      0
5              0.0             0.0                1.0      0

Se han sustituido los elementos nulos de MMSE y se ha cambiado por la media de MMSE. Sólo son dos datos, pero tenemos pocas filas. Mejor salvar lo que se pueda.

En cambio, se consideró que el número de datos faltantes en SES era demasiado alto como para sustituirlo por la media. Se retiraron las filas con datos nulos en esta columna. Se podría retirar la columna y mantener el resto de datos de esas filas.

Se han eliminado Subject ID y MRI ID porque son id de usaurios. No ayudará a predecir mejor el resultado.

Se ha eliminado la columna que dice si son diestros o zurdos. Todos eran diestro, no aportaba información y sería ruido.

Se ha codificado la columna de M/F con 0 y 1 al ser un columna con datos binarios.

Se ha pasado a entero la columna de SES y MMSE

Se ha hecho One hot encoding con la columna de Group

### Ejercicio 2

#### Perceptrón multicapa

Llega al 65% de predicción

In [79]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import random
from sklearn.metrics import confusion_matrix, accuracy_score


debug = False

if debug:
    import matplotlib.pyplot as plt
    import seaborn as sns
    
    correlation_matrix = datos.corr()

    plt.figure(figsize=(20,20))
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
    plt.title('Matriz de Correlación')
    plt.show()
    

TAM_ENTRENAMIENTO=0.8

arrayToGuess = ["Group_Converted", "Group_Demented", "Group_Nondemented"]

#target= Y[arrayToGuess]
target= Y["Group"]

semilla = 42

x_train, x_test, y_train, y_test = train_test_split(X, target, train_size = TAM_ENTRENAMIENTO, random_state = semilla)

if debug:
    param_grid = {
        'hidden_layer_sizes': [
            (16,),
            (32,),
            (64,),
            (32,16),
            (64, 32)
            ],
        'solver':['adam','sgd','lbfgs'],
        'activation':['relu','identity','logistic','tanh'],
        'alpha': [0.00001,0.0001, 0.001, 0.01],
        'max_iter': [300,400,500,1000,2000,10000],
        'early_stopping':[True,False]
    }

    mlp_param = MLPClassifier(random_state=semilla)

    from sklearn.model_selection import RandomizedSearchCV

    random_search = RandomizedSearchCV(
        estimator=mlp_param,
        param_distributions=param_grid,
        n_iter=50,  # prueba con 50 combinaciones
        cv=5,
        scoring='accuracy',
        verbose=1,
        random_state=semilla,
        refit=True,
        n_jobs=-1
    )
    random_search.fit(x_train, y_train)
    print("Mejores parámetros")
    print(random_search.best_params_)
    print(random_search.best_score_)

print(f"tamaño de los datos de entrenamiento:{x_train.shape}")
print(f"tamaño de los datos de test:{x_test.shape}")

#red neuronal (MLPClassifier) 

#'solver': 'adam', 'max_iter': 2000, 'hidden_layer_sizes': 64, 'alpha': 0.001, 'activation': 'logistic'
mlp = MLPClassifier(hidden_layer_sizes=(32,), activation='logistic', max_iter=10000,solver='lbfgs',early_stopping=True,alpha=1e-05,random_state=semilla)
mlp.fit(x_train, y_train)
y_pred_mlp = mlp.predict(x_test)

print(f'Precisión: {accuracy_score(y_test, y_pred_mlp)}')
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred_mlp))




tamaño de los datos de entrenamiento:(283, 11)
tamaño de los datos de test:(71, 11)
Precisión: 0.8873239436619719
Matriz de confusión:
 [[35  1  1]
 [ 0 25  1]
 [ 4  1  3]]
